# Текстовые команды. Можете добовлять их сколько угодно. Данные команды не реализуют какой либо фнкционал, и
# могут использовтся только как "вопрос - ответ".
start = "Привет! Я бот который будет пирсыталь увдомления в Telegram о новых сериях твоего любимого аниме. Можешь подробнее узнать о моих функциях с помощью команды /help."
help  ="""Вот что я умею:
/start -
/help -
/subscribe - будет прислыать увдеомления о новых сериях данного аниме.
/unsubscribe - перестанет проверять и прсылать увдомления о новых сериях данного аниме"""

# Служебные команды. Распознаются программой и выполняют заложеные сенарии. Переписвание значений скорее всего
# приведёт к сбою. Вы можете только изменить название команды.
subscribe = "#subscribe"
unsubscribe = "#unsubscribe"
list = "#list"
